### PR TITLE
Add validation of regression models and test them

### PR DESCRIPTION
**Pull request by fullflu**
Test regression models

Ref: #63

### CODE REVIEW

**Comment by fullflu** [comment]
```
% pytest tests/ope/test_regression_models.py -s
====================================================== test session starts ======================================================
platform darwin -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kt/projects/zr-obp
collected 42 items                                                                                                              

tests/ope/test_regression_models.py .........................................gt_mean: 0.06503130170983691
Dr criteria is satisfied with probability 0.86701 ------ model: logistic_regression (normal),
Dr criteria is satisfied with probability 0.92146 ------ model: lightgbm (normal),
Dr criteria is satisfied with probability 0.92802 ------ model: random_forest (normal),
Dr criteria is satisfied with probability 0.86784 ------ model: logistic_regression (iw),
Dr criteria is satisfied with probability 0.92398 ------ model: lightgbm (iw),
Dr criteria is satisfied with probability 0.93083 ------ model: random_forest (iw),
Dr criteria is satisfied with probability 0.86856 ------ model: logistic_regression (mrdr),
Dr criteria is satisfied with probability 0.92643 ------ model: lightgbm (mrdr),
Dr criteria is satisfied with probability 0.93748 ------ model: random_forest (mrdr),
AUC of logistic_regression_normal is 0.7967672226104708
AUC of lightgbm_normal is 0.7766957216944005
AUC of random_forest_normal is 0.7839543007549834
AUC of logistic_regression_iw is 0.7966112254190814
AUC of lightgbm_iw is 0.7756874411189096
AUC of random_forest_iw is 0.7895450814531733
AUC of logistic_regression_mrdr is 0.7960282189665153
AUC of lightgbm_mrdr is 0.7692323963201187
AUC of random_forest_mrdr is 0.7878674506406875
.

====================================================== 42 passed in 11.22s ======================================================
```

**Comment by usaito** [comment]
@fullflu 

Thanks! Can you address the following points?

[nits]

## regression_model.py

- I think `f"position elements must be smaller than len_list, but the maximum value is {position.max()} (> {self.len_list})"` is better
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/obp/ope/regression_model.py#L147
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/obp/ope/regression_model.py#L319

- `"when fitting_method is either 'iw' or 'mrdr', action_dist (a 3-dimensional ndarray) must be given"` is better
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/obp/ope/regression_model.py#L152
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/obp/ope/regression_model.py#L324

- I think `"shape of action_dist must be (n_rounds, n_actions, len_list)=({n_rounds, self.n_actions, self.len_list}), but is action_dist.shape"` is better
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/obp/ope/regression_model.py#L156
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/obp/ope/regression_model.py#L328

## test_regression_model.py

- you can use `np.random.choice(n_actions, size=n_rounds)` (the same comment is applied to other parts)
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/tests/ope/test_regression_models.py#L102


[ask]

- Why do you separate the case when `fitting_method="normal"` and the other?
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/tests/ope/test_regression_models.py#L703-L726
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/tests/ope/test_regression_models.py#L757-L780

- I think  `len_list=bandit_feedback["position"].ndim` should be `len_list=bandit_feedback["position"].max() + 1`. Is it a mistake or do you intended to do this?
https://github.com/fullflu/zr-obp/blob/eee41004287d342c237dc114cc8c3a1f7db96e66/tests/ope/test_regression_models.py#L808

**Comment by fullflu** [comment]
@usaito 
I fixed several codes based on your comments!

> Why do you separate the case when fitting_method="normal" and the other? I couldn't find the reason.

Oh, this is exactly the meaningless code...
I removed unnecessary arguments when  fitting_method="normal", and fixed several test cases due to the change.

> I think len_list=bandit_feedback["position"].ndim should be len_list=bandit_feedback["position"].max() + 1. Is it a mistake or did you intend to do this?

I'm sorry that it is a mistake. I fixed them!

**Comment by usaito** [comment]
@fullflu Thank you for answering my questions! LTGM!

Can you resolve the conflicts?

**Pull request merged**
