### PR TITLE
Add input validation to ope.meta.py and test the validation

### PR DESCRIPTION
**Pull request by fullflu**
# Overview
- fix validation of ope.meta.py
- fix test_meta.py to check the validation

# Testing plan
- assert -> ValueError
- parametrize invalid data and valid data
- add test

### CODE REVIEW

**Comment by fullflu** [comment]
```
 % pytest -s                       
================================================== test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kt/projects/zr-obp
collected 96 items                                                                                                      

tests/dataset/test_synthetic.py .....
tests/ope/test_all_estimators.py .gt_mean: 0.6045989398691939, 3 * gt_std / sqrt(n): 0.006613877704726712
estimated_value: 0.6085633674700573 ------ estimator: ipw, 
estimated_value: 0.6075271140468232 ------ estimator: snipw, 
estimated_value: 0.6045989398691939 ------ estimator: dm, 
estimated_value: 0.6068435736544552 ------ estimator: dr, 
estimated_value: 0.6045989398691939 ------ estimator: dr-os, 
estimated_value: 0.6037623157105296 ------ estimator: switch-dr, 
estimated_value: 0.6068397515225818 ------ estimator: sndr, 
..
tests/ope/test_dm_estimators.py .
tests/ope/test_dr_estimators.py .....
tests/ope/test_ipw_estimators.py ..
tests/ope/test_meta.py .........................................
tests/ope/test_regression_models.py gt_mean: 0.06503130170983691
Dr criteria is satisfied with probability 0.86701 ------ model: logistic_regression (normal),
Dr criteria is satisfied with probability 0.92146 ------ model: lightgbm (normal),
Dr criteria is satisfied with probability 0.92802 ------ model: random_forest (normal),
Dr criteria is satisfied with probability 0.86784 ------ model: logistic_regression (iw),
Dr criteria is satisfied with probability 0.92398 ------ model: lightgbm (iw),
Dr criteria is satisfied with probability 0.93083 ------ model: random_forest (iw),
Dr criteria is satisfied with probability 0.86856 ------ model: logistic_regression (mrdr),
Dr criteria is satisfied with probability 0.92643 ------ model: lightgbm (mrdr),
Dr criteria is satisfied with probability 0.93748 ------ model: random_forest (mrdr),
AUC of logistic_regression_normal is 0.7967672226104708
AUC of lightgbm_normal is 0.7766957216944005
AUC of random_forest_normal is 0.7839543007549834
AUC of logistic_regression_iw is 0.7966112254190814
AUC of lightgbm_iw is 0.7756874411189096
AUC of random_forest_iw is 0.7895450814531733
AUC of logistic_regression_mrdr is 0.7960282189665153
AUC of lightgbm_mrdr is 0.7692323963201187
AUC of random_forest_mrdr is 0.7878674506406875
.
tests/policy/test_contextfree.py ...........
tests/policy/test_linear.py ............
tests/policy/test_logistic.py .........
[sample_action]: 100%|███████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 2945.44it/s]
.

================================================== 96 passed in 10.18s ==================================================
```

**Comment by usaito** [comment]
@fullflu Thanks! Can you fix the following minor points?

## meta.py

[nits]
- [] `must be the same as` is better than `needs to be equal to`
https://github.com/fullflu/zr-obp/blob/653d43239f55fc716f62e7d1aec7fa1c3da11b20/obp/ope/meta.py#L107
https://github.com/fullflu/zr-obp/blob/653d43239f55fc716f62e7d1aec7fa1c3da11b20/tests/ope/test_meta.py#L253

## test_meta.py

[nits]

- [] `hoge_input_of_evaluation_performance` should be `_input_of_evaluate_performance_of_estimators`
https://github.com/fullflu/zr-obp/blob/653d43239f55fc716f62e7d1aec7fa1c3da11b20/tests/ope/test_meta.py#L570
https://github.com/fullflu/zr-obp/blob/653d43239f55fc716f62e7d1aec7fa1c3da11b20/tests/ope/test_meta.py#L581

- [] `_create_estimator_inputs function is called in the following functions` is better
https://github.com/fullflu/zr-obp/blob/653d43239f55fc716f62e7d1aec7fa1c3da11b20/tests/ope/test_meta.py#L292
https://github.com/fullflu/zr-obp/blob/653d43239f55fc716f62e7d1aec7fa1c3da11b20/tests/ope/test_meta.py#L352

**Comment by fullflu** [comment]
@usaito 

Thank you for your review!

>  hoge_input_of_evaluation_performance should be _input_of_evaluate_performance_of_estimators

Could you tell me the details about this review?
I named their variables because L570 is an invalid input and L581 is a valid input, and I intended to use them in different manners (that is why their variable names are different).

I'm sorry if I could not understand your review point ><

**Comment by usaito** [comment]
@fullflu 
Sorry for the unclear review.. 
I was just saying that we should use
`valid_input_of_evaluate_performance_of_estimators` and `invalid_input_of_evaluate_performance_of_estimators`, respectively because the function you are testing is `evaluate_performance_of_estimators` while you use `_evaluation_performance` to define the lists

**Comment by fullflu** [comment]
@usaito 

I got it! Thank you!

By the way, I created another branch from this PR and added several validations here: #63 

So I'm planning to replace `evaluate_performance` with `evaluate_performance_of_estimators` in the PR of #63,  and to close this PR (#58) if this PR has no problem  without `evaluate_performance_of_estimators`.

How about it?

**Comment by usaito** [comment]
@fullflu 

Ok, no problem. Can I review #63 right now?

**Comment by fullflu** [comment]
#63

**Pull request closed without merging**
