### PR TITLE
Add input validation to ope.estimators.py and test the validation 

### PR DESCRIPTION
**Pull request by fullflu**
# Overview
- fix validation of ope.estimators.py and utills.py
- fix test_*_estimators.py to check the validation

# Testing plan
- assert -> ValueError
- parametrize invalid data and valid data
- add test

Ref: #58

### CODE REVIEW

**Comment by fullflu** [comment]
```
% pytest -s           
==================================================== test session starts ====================================================
platform darwin -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kt/projects/zr-obp
collected 158 items                                                                                                         

tests/dataset/test_synthetic.py .....
tests/ope/test_all_estimators.py ......................gt_mean: 0.6045989398691939, 3 * gt_std / sqrt(n): 0.006613877704726712
estimated_value: 0.6085633674700573 ------ estimator: ipw, 
estimated_value: 0.6075271140468232 ------ estimator: snipw, 
estimated_value: 0.6045989398691939 ------ estimator: dm, 
estimated_value: 0.6068435736544552 ------ estimator: dr, 
estimated_value: 0.6045989398691939 ------ estimator: dr-os, 
estimated_value: 0.6037623157105296 ------ estimator: switch-dr, 
estimated_value: 0.6068397515225818 ------ estimator: sndr, 
..
tests/ope/test_dm_estimators.py ....
tests/ope/test_dr_estimators.py ............................
tests/ope/test_ipw_estimators.py .................
tests/ope/test_meta.py .........................................
tests/ope/test_regression_models.py gt_mean: 0.06503130170983691
Dr criteria is satisfied with probability 0.86701 ------ model: logistic_regression (normal),
Dr criteria is satisfied with probability 0.92146 ------ model: lightgbm (normal),
Dr criteria is satisfied with probability 0.92802 ------ model: random_forest (normal),
Dr criteria is satisfied with probability 0.86784 ------ model: logistic_regression (iw),
Dr criteria is satisfied with probability 0.92398 ------ model: lightgbm (iw),
Dr criteria is satisfied with probability 0.93083 ------ model: random_forest (iw),
Dr criteria is satisfied with probability 0.86856 ------ model: logistic_regression (mrdr),
Dr criteria is satisfied with probability 0.92643 ------ model: lightgbm (mrdr),
Dr criteria is satisfied with probability 0.93748 ------ model: random_forest (mrdr),
AUC of logistic_regression_normal is 0.7967672226104708
AUC of lightgbm_normal is 0.7766957216944005
AUC of random_forest_normal is 0.7839543007549834
AUC of logistic_regression_iw is 0.7966112254190814
AUC of lightgbm_iw is 0.7756874411189096
AUC of random_forest_iw is 0.7895450814531733
AUC of logistic_regression_mrdr is 0.7960282189665153
AUC of lightgbm_mrdr is 0.7692323963201187
AUC of random_forest_mrdr is 0.7878674506406875
.
tests/policy/test_contextfree.py ...........
tests/policy/test_linear.py ............
tests/policy/test_logistic.py .........
[sample_action]: 100%|███████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 2941.31it/s]
.

=================================================== 158 passed in 15.08s ====================================================
```

**Comment by usaito** [comment]
@fullflu 

Thanks! 

Can you address the following minor points?

[nits]

- [ ] `Optional[ValueError]` not `Optional[AssertionError]`
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/obp/utils.py#L289

- [ ] type: `greater` is correct, not `greator`
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/obp/utils.py#L342
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/tests/ope/test_all_estimators.py#L102 

- [ ] there is an inconsistent coding with the other parts here
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/obp/utils.py#L346-L349

I recommend

```python
If estimated_rewards_by_reg_model is not None:
	if estimated_rewards_by_reg_model.shape != action_dist.shape:
		raise hogehoge
```

- [ ] it is better to use `np.zeros(5, dtype=int) - 1` not `np.zeros(5) - 1`
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/tests/ope/test_all_estimators.py#L73

- [ ] You can use `np.random.choice(3, size=5)` instead of `np.random.choice([0, 1, 2], size=5)` (the same comment is applied to test_ipw_estimators.py and test_dr_estimators.py)
e.g.,
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/tests/ope/test_all_estimators.py#L112

- [ ] How about using `np.random.choice(4, size=5),` instead of `np.zeros(5, dtype=int),` to define a valid action array? (the same comment is applied to test_ipw_estimators.py and test_dr_estimators.py)
e.g., 
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/tests/ope/test_all_estimators.py#L109
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/tests/ope/test_all_estimators.py#L118
https://github.com/fullflu/zr-obp/blob/944061da08960f6c9265504f3e41e7247f9710eb/tests/ope/test_all_estimators.py#L127

**Comment by fullflu** [comment]
@usaito 
OK, I fixed several codes based on your comments!
I also removed switch-ipw and added relative estimated policy value.

I hope you to review them again !><

**Comment by usaito** [comment]
@fullflu Thanks! LGTM!

**Pull request merged**
