### PR TITLE
Test dataset real

### PR DESCRIPTION
**Pull request by nmasahiro**
## Overview

Add several tests for the dataset **real** module.

```
$ pytest -s

============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /Users/a14752/Documents/research/OPE/code/zr-obp/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/a14752/Documents/research/OPE/code/zr-obp
collecting ... collected 4 items

tests/test/dataset/test_real.py::test_real_init 
tests/test/dataset/test_real.py::test_obtain_batch_bandit_feedback 
tests/test/dataset/test_real.py::test_calc_on_policy_policy_value_estimate 
tests/test/dataset/test_real.py::test_sample_bootstrap_bandit_feedback 
```

## Review points
* Testing structure
* Testing code

## Remark
* This test has verified the behavior of the algorithm, but not the performance.

### CODE REVIEW

**Comment by usaito** [comment]
@nmasahiro Thanks! Can you address the following points?

[must]
`test_real.py` exists in the `tests/test/dataset` directory. Can you move it into `tests/dataset`?

[ask]
why are you using `opd` instead of `obd`?
https://github.com/nmasahiro/zr-obp/blob/bfb03c9fd0753ee5a54354f581f29ac5518059ac/tests/test/dataset/test_real.py#L24

**Comment by usaito** [comment]
[nits]

Can you also fix this ref? the new title is `Open Bandit Dataset and Pipeline: Towards Realistic and Reproducible Off-Policy Evaluation`
https://github.com/nmasahiro/zr-obp/blob/bfb03c9fd0753ee5a54354f581f29ac5518059ac/obp/dataset/real.py#L45

**Comment by nmasahiro** [comment]
@usaito Thank you for the review!
> why are you using opd instead of obd?

Sorry, this is my mistake.
I applied all your suggestions, so please check.

**Comment by usaito** [comment]
@nmasahiro  Thanks! LGTM!

**Pull request merged**
