### PR TITLE
Refactoring and add flake8

### PR DESCRIPTION
**Pull request by nmasahiro**
## Overview
* improve maintainability
  * ef12cf06cb89b37dd64fc5b6bf385dbbc15fdb8e: change the type of `reward_type` to Enum
  * 83013355a91ee884f48b83d817c8988c4af9b180: change the type of `policy_type` to Enum
* remove an unused function 6bc70e617cf406997741aa8a32fb5adac093b47b
* remove flake8 errors completely; the important points are:
  * 498fa285bc421f9948235732a25bfb7b9b1ad7f5, 8e42430714ffc3b450d3dd03acab507e666b6be6, 81b79b318c11c24b67f387a074ba3d2f2601ddd8, b3d199fd5f7cdefe28a27b83bd76df1b60b151c9: change `__init__.py`
  * 7ed38109da24208daab60135c47fafc003b0ee8f: ignore W605, which is originated from math equations
*  https://github.com/st-tech/zr-obp/issues/83 436dc900b9a1af49f390f8499159b730459212c3
* add flake8 to github actions: 7e998f7e1e276ef3fcdcf31f544a9911074f8678
* fix CONTRIBUTING.md 1af219e2cece95564b4d2ee539c7d95cbbebfb05

### CODE REVIEW

**Comment by usaito** [comment]
@nmasahiro Thanks! Can you fix https://github.com/st-tech/zr-obp/issues/83 also?

**Comment by nmasahiro** [comment]
@usaito 
Sure.
I've fixed it, and refactoring several implementations.
Can you review this PR?

**Comment by usaito** [comment]
@nmasahiro Great! LGTM!

Can you finally update https://github.com/st-tech/zr-obp/blob/master/CONTRIBUTING.md to finalize this PR?
I think `(to appear)` statement is no longer necessary.

**Comment by usaito** [comment]
Oops, it may be implement `PolicyType` as below (https://github.com/nmasahiro/zr-obp/blob/refactoring/obp/policy/policy_type.py). how do you think about that?
(I'm sorry if I make a mistake here..)

```python
import enum, auto


class PolicyType(enum.Enum):
    """Policy type.
    Attributes
    ----------
    CONTEXT_FREE:
        The policy type is contextfree.
    CONTEXTUAL:
        The policy type is contextual.
    OFFLINE:
        The policy type is offline.
    """

    CONTEXT_FREE = auto()
    CONTEXTUAL = auto()
    OFFLINE = auto()
```

or

```python
import enum


class PolicyType(enum.Enum):
    """Policy type.
    Attributes
    ----------
    CONTEXT_FREE:
        The policy type is contextfree.
    CONTEXTUAL:
        The policy type is contextual.
    OFFLINE:
        The policy type is offline.
    """

    CONTEXT_FREE = "context_free"
    CONTEXTUAL = "contextual"
    OFFLINE = "offline"
```

**Comment by nmasahiro** [comment]
> @nmasahiro Great! LGTM!
> 
> Can you finally update https://github.com/st-tech/zr-obp/blob/master/CONTRIBUTING.md to finalize this PR?
> I think `(to appear)` statement is no longer necessary.

Thanks for noting it. I've fixed it.

**Comment by nmasahiro** [comment]
> how do you think about that?

The motivation of making `PolicyType` the current implementation is that, in my understanding, PolicyType is used only inside OSS, and not used for users. In this case, the value (e.g., `"context_free"`, `"contextual"`) is not helpful.

On the other hand, [RewardType receives input from the user and makes a judgment based on it](https://github.com/st-tech/zr-obp/blob/f03aeb1bb0364a7242ab7f393c6417127d1f3b7e/obp/dataset/synthetic.py#L37-L41), so specific values such as `"binary"` and `"continuous"` are needed.

That said, I have no strong opinion. If you wish, I can change it as above :)

**Comment by usaito** [comment]
@nmasahiro Got it. Then, how about using `auto` function as I described in the first place?
Because, here, indies given to the policy types (e.g., `CONTEXT_FREE = 1`) have no specific meaning, right?

**Comment by nmasahiro** [comment]
I didn't have sufficient knowledge about `auto()` method.
You are completely right, thank you for noting it.
I've fixed it.

**Comment by usaito** [comment]
@nmasahiro Thanks! I'll merge this PR.

**Pull request merged**
