### PR TITLE
Add several tests of ope estimators

### PR DESCRIPTION
**Pull request by fullflu**
# Overview

Add several tests of ope estimators and regression_models using pytest.

```
$pytest -s
================================================== test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kt/projects/zr-obp
collected 16 items                                                                                                      

tests/ope/test_all_estimators.py .gt_mean: 0.6045989398691939, 3 * gt_std / sqrt(n): 0.006613877704726712
estimated_value: 0.6085633674700573 ------ estimator: ipw, 
estimated_value: 0.6075271140468232 ------ estimator: snipw, 
estimated_value: 0.6045989398691939 ------ estimator: dm, 
estimated_value: 0.6068435736544552 ------ estimator: dr, 
estimated_value: 0.6045989398691939 ------ estimator: dr-os, 
estimated_value: 0.6037623157105296 ------ estimator: switch-dr, 
estimated_value: 0.6068397515225818 ------ estimator: sndr, 
..
tests/ope/test_dm_estimators.py .
tests/ope/test_dr_estimators.py .....
tests/ope/test_ipw_estimators.py ..
tests/ope/test_meta.py .....
tests/ope/test_regression_models.py gt_mean: 0.00604598939869194, 5 * gt_std / sqrt(10000): 0.00011023129507877855
Dr criteria is satisfied with probability 0.91204 ------ model: logistic_regression (normal),
Dr criteria is satisfied with probability 0.93626 ------ model: lightgbm (normal),
Dr criteria is satisfied with probability 0.94046 ------ model: random_forest (normal),
Dr criteria is satisfied with probability 0.90884 ------ model: logistic_regression (iw),
Dr criteria is satisfied with probability 0.93774 ------ model: lightgbm (iw),
Dr criteria is satisfied with probability 0.93989 ------ model: random_forest (iw),
Dr criteria is satisfied with probability 0.90665 ------ model: logistic_regression (mrdr),
Dr criteria is satisfied with probability 0.94352 ------ model: lightgbm (mrdr),
Dr criteria is satisfied with probability 0.93458 ------ model: random_forest (mrdr),
AUC of logistic_regression_normal is 0.590121843138131
AUC of lightgbm_normal is 0.5770354357977523
AUC of random_forest_normal is 0.522368940426451
AUC of logistic_regression_iw is 0.5875412412211124
AUC of lightgbm_iw is 0.5858971780950466
AUC of random_forest_iw is 0.5292077216971647
AUC of logistic_regression_mrdr is 0.5802295357895599
AUC of lightgbm_mrdr is 0.5944563606437727
AUC of random_forest_mrdr is 0.5376533279710436

================================================== 17 passed in 9.64s ===================================================
```

# Review points

- Testing structure
- Testing code
- Naming of variables and methods
- Testing comment

# Remark

- added `__all_estimators__` in `obb/ope/__init__.py` to test all_estimators (ref: [category encoders](https://github.com/scikit-learn-contrib/category_encoders/blob/master/category_encoders/__init__.py#L31)
- skipped the performance tests of `ReplayMethod` and `SwitchInverseProbabilityWeighting` because they are known to be biased in this experimental setting
- scenarios where `len_list > 1` cannot be considered (future work)
- flake8 warning of W503 happens: `tests/ope/test_all_estimators.py:115 (&119) :13: W503 line break before binary operator`
- three regression models (Logistic regression, Random forests, and Lightgbm) with three fit_methods (normal, iw, and mrdr) are tested

# Details

## conftest.py
- generate synthetic data used in the following tests (linear behavior policy and logistic reward)
- adjust expected_reward to test regression models using doubly robust criteria (fixed_synthetic_bandit_feedback)

## test_meta.py
- check the output format of several methods of OffPolicyEvaluation using mock estimators
- check the behavior of `__post_init__`

## test_all_estimators.py
- check the behavior of fixtures
- check the response format of estimated_policy_values and estimated_intervals of `__all_estimators__` using `meta.py`
- check the performance of ope estimators when the evaluation policy is `Random`, **which enables us to check the quality of new estimators easily without adding new tests about the estimators**

## test_dm_estimators.py
- validate the input data format of `DirectMethod`
- check the performance of `DirectMethod`

## test_ipw_estimators.py
- validate the input data format of `InverseProbabilityWeighting` and `SelfNormalizedInverseProbabilityWeighting`
- check the normalization effect

## test_dr_estimators.py
- validate the input data format of DoublyRobust-like estimators
- compare the response value using special case (e.g., `SwitchInverseProbabilityWeighting(tau=0)` should be the same as `DirectMethod`

## test_regression_models.py
- validate ROC-AUC scores of binary prediction models (should be greater than 0.5)
- check the probability that the models satisfy doubly robust criteria  (|\hat{q} - q| <= |q| is satisfied with probability at least 0.9, where q is an expected reward)

### CODE REVIEW

**Comment by usaito** [comment]
@fullflu 
Thanks!

## conftest.py

[nits]
should remove `WIP`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L21

`# make the expected reward of synthetic bandit feedback close to that of the Open Bandit Dataset` is better than `# adjust expected reward of synthetic bandit feedback` i think
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L89

Should be `#logistic evaluation policy`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L141
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L162

Should be `#random evaluation policy`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L168

## test_all_estimators.py

[imo]
I think `ground_truth_policy_value` should be `q_pi_e`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L43

I think you should set the `random_state` argument when testing the `estimate_intervals` method
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L98

I think `def test_performance_of_ope_estimators_using_random_evaluation_policy` is appropriate here
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L32

I think `def test_response_format_of_ope_estimators_using_random_evaluation_policy` is appropriate here
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L76

[nits]
`# test most of the estimators...` is better than `# extract most of all estimators...`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L49
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L86

`#check the keys of the output directory of the estimate_intervals method` is better than `# check key of confidence intervals`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L103

`#check the relationship between the means and the confidence bounds estimated by OPE estimators` is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L107

## test_dm_estimator.py

[imo]
I think `ground_truth_policy_value` should be `q_pi_e`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L21

[nits]
`DM should be perfect when the regression model is perfect` is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L49
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L57

`unnecessary` is better than `unused`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L50


## test_ipw_estimators.py

[imo]
How about using `the boundedness of snipw` rather than `the range of snipw`? (following https://arxiv.org/pdf/1906.03735.pdf)
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L56
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L52

[nits]
`ipw variants` is better than `ipw-like estimators`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L22

`necessary` is better than `used`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L38

`#prepare ipw and snipw`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L59

`check the boundedness of snipw` is better than `check the normalization effect`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L69

`#estimated policy value of snipw should be smaller than 1 (because of its 1-boundedness)` is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L78

[ask]
I don't know why this verification is necessary..
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L74


## test_dr_estimators.py

[must]
sndr has the 2-boundedness not the 1-boundedness. Thus, `estimated_policy_value <= 1` should be `estimated_policy_value <= 2`. See https://arxiv.org/pdf/1906.03735.pdf
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L98

[imo]
How about using `the boundedness of sndr` rather than `the range of sndr`?
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L72
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L76

swipw and swdr are ambiguous. I think it's better to clearify these by using `switch_ipw` and `switch_dr`. How do you think about this?
e.g., https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L132

[nits]
`dr variants` is better than `dr-like estimators`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L37

Should be `require` (not `requires`)
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L51

`necessary` is better than `used`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L57

`check the boundedness of sndr` is better than `check the normalization effect`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L90

`#estimated policy value of sndr should be smaller than 2 (because of its 2-boundedness)` is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L99

`the swipw shrinkage estimators` should be `the swipw estimators`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L136

`the dr swdr` should be `the switch dr`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L166

[ask]
I don't know why this verification is necessary..
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L74



## test_meta.py

[imo]
I think you should define `pd.DataFrame(performance, index=["relative-ee"]).T` by yourself as you did in `test_meta_summarize_off_policy_estimates`. How do you think about this?
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L344


[nits]

`a wrong value`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L222
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L225
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L237
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L241
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L254



## test_regression_models.py

[imo]
I think `ground_truth_policy_value` should be `q_pi_e`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L38

[nits]

`with a high probability`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L52

`DR criteria should be satisfied with a probability at least..` is better than `Dr criteria should not be larger then 0 with probability..`
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L102

Should be `greater` (typo)
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L108


[ask]
I think AUCs are too small (0.52..~0.59..) given that we use the simple synthetic data. Do you know why?

**Comment by fullflu** [comment]
## conftest.py
[nits]

- [ ]  WIP should be removed
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L21

- [ ]  # make the expected reward of synthetic bandit feedback close to that of the Open Bandit Dataset is better than # adjust expected reward of synthetic bandit feedback i think
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L89

- [ ]  Should be #logistic evaluation policy -> remove logistic evaluation policy
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L141
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L162

- [ ]  Should be #random evaluation policy
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/conftest.py#L168

- [ ] test_all_estimators.py

[imo]

- [ ]  I think ground_truth_policy_value should be q_pi_e
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L43

- [ ]  I think you should set the random_state argument when testing the estimate_intervals method
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L98

-- [ ]  I think def test_performance_of_ope_estimators_using_random_evaluation_policy is appropriate here
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L32

- [ ]  I think def test_response_format_of_ope_estimators_using_random_evaluation_policy is appropriate here
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L76

[nits]

- [ ]  # test most of the estimators... is better than # extract most of all estimators...
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L49
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L86

- [ ]  #check the keys of the output directory of the estimate_intervals method is better than # check key of confidence intervals
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L103

- [ ]  #check the relationship between the means and the confidence bounds estimated by OPE estimators is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_all_estimators.py#L107

## test_dm_estimator.py
[imo]

- [ ]  I think ground_truth_policy_value should be q_pi_e
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L21

[nits]
- [ ]  DM should be perfect when the regression model is perfect is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L49
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L57

- [ ]  unnecessary is better than unused
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dm_estimators.py#L50

## test_ipw_estimators.py
[imo]

- [ ]  How about using the boundedness of snipw rather than the range of snipw? (following https://arxiv.org/pdf/1906.03735.pdf)
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L56
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L52
[nits]

- [ ]  ipw variants is better than ipw-like estimators
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L22

- [ ]  necessary is better than used
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L38

- [ ]  #prepare ipw and snipw
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L59

- [ ]  check the boundedness of snipw is better than check the normalization effect
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L69

- [ ]  #estimated policy value of snipw should be smaller than 1 (because of its 1-boundedness) is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L78

[ask]

- [ ]  I don't know why this verification is necessary..
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L74
test_dr_estimators.py

[must]

- [ ]  sndr has the 2-boundedness not the 1-boundedness. Thus, estimated_policy_value <= 1 should be estimated_policy_value <= 2. See https://arxiv.org/pdf/1906.03735.pdf
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L98
[imo]

- [ ]  How about using the boundedness of sndr rather than the range of sndr?
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L72
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L76

- [ ]  swipw and swdr are ambiguous. I think it's better to clearify these by using switch_ipw and switch_dr. How do you think about this?
e.g., https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L132

[nits]

- [ ]  dr variants is better than dr-like estimators
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L37

- [ ]  Should be require (not requires)
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L51

- [ ]  necessary is better than used
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L57

- [ ]  check the boundedness of sndr is better than check the normalization effect
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L90

- [ ]  #estimated policy value of sndr should be smaller than 2 (because of its 2-boundedness) is better
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L99

- [ ]  the swipw shrinkage estimators should be the swipw estimators
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L136

- [ ]  the dr swdr should be the switch dr
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_dr_estimators.py#L166

[ask]

- [ ]  I don't know why this verification is necessary..
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_ipw_estimators.py#L74
test_meta.py

[imo]

- [ ]  I think you should define pd.DataFrame(performance, index=["relative-ee"]).T by calculating the relative estimation errors by yourself as you did in test_meta_summarize_off_policy_estimates. How do you think about this?
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L344
[nits]

- [ ]  a wrong value
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L222
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L225
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L237
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L241
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_meta.py#L254
test_regression_models.py
[imo]

- [ ]  I think ground_truth_policy_value should be q_pi_e
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L38
[nits]

- [ ]  with a high probability
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L52

 - [ ]  ci_bound is unnecessary here
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L48

- [ ]  DR criteria should be satisfied with a probability at least.. is better than Dr criteria should not be larger then 0 with probability..
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L102

- [ ]  Should be greater (typo)
https://github.com/fullflu/zr-obp/blob/f81bbef20424c2d634204e70e2557a3e0038d0da/tests/ope/test_regression_models.py#L108

[ask]

- [ ]  I think AUCs are too small (0.52..~0.59..) given that we use the simple synthetic data. Do you know why?

**Comment by fullflu** [comment]
@usaito 
>  #estimated policy value of snipw should be smaller than 1 (because of its 1-boundedness) is better

`x is smaller than 1` means `x < 1`,  but I think that the 1-boundedness means `x <= 1`.

There would be two options in this case:
- `should be smaller than or equal to 1`
- `should not be greater than 1`

I'd like to hear your opinion which to use.

**Comment by usaito** [comment]
@fullflu 

Oops.. I prefer `should be smaller than or equal to 1` to `should not be greater than 1` because `not be greater` is an indirect expression.

**Comment by usaito** [comment]
@fullflu 

I merged nomura-san's PRs and realized that he implemented his test codes in the `test` directory while you use the `tests` directory. Can you fix this inconsistency later? I think `tests` is appropriate.

**Comment by fullflu** [comment]
```
% pytest -s       
================================================== test session starts ==================================================
platform darwin -- Python 3.9.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kt/projects/zr-obp
collected 17 items                                                                                                      

tests/ope/test_all_estimators.py .gt_mean: 0.6045989398691939, 3 * gt_std / sqrt(n): 0.006613877704726712
estimated_value: 0.6085633674700573 ------ estimator: ipw, 
estimated_value: 0.6075271140468232 ------ estimator: snipw, 
estimated_value: 0.6045989398691939 ------ estimator: dm, 
estimated_value: 0.6068435736544552 ------ estimator: dr, 
estimated_value: 0.6045989398691939 ------ estimator: dr-os, 
estimated_value: 0.6037623157105296 ------ estimator: switch-dr, 
estimated_value: 0.6068397515225818 ------ estimator: sndr, 
..
tests/ope/test_dm_estimators.py .
tests/ope/test_dr_estimators.py .....
tests/ope/test_ipw_estimators.py ..
tests/ope/test_meta.py .....
tests/ope/test_regression_models.py gt_mean: 0.06503130170983691
Dr criteria is satisfied with probability 0.86701 ------ model: logistic_regression (normal),
Dr criteria is satisfied with probability 0.92146 ------ model: lightgbm (normal),
Dr criteria is satisfied with probability 0.92802 ------ model: random_forest (normal),
Dr criteria is satisfied with probability 0.86784 ------ model: logistic_regression (iw),
Dr criteria is satisfied with probability 0.92398 ------ model: lightgbm (iw),
Dr criteria is satisfied with probability 0.93083 ------ model: random_forest (iw),
Dr criteria is satisfied with probability 0.86856 ------ model: logistic_regression (mrdr),
Dr criteria is satisfied with probability 0.92643 ------ model: lightgbm (mrdr),
Dr criteria is satisfied with probability 0.93748 ------ model: random_forest (mrdr),
AUC of logistic_regression_normal is 0.7967672226104708
AUC of lightgbm_normal is 0.7766957216944005
AUC of random_forest_normal is 0.7839543007549834
AUC of logistic_regression_iw is 0.7966112254190814
AUC of lightgbm_iw is 0.7756874411189096
AUC of random_forest_iw is 0.7895450814531733
AUC of logistic_regression_mrdr is 0.7960282189665153
AUC of lightgbm_mrdr is 0.7692323963201187
AUC of random_forest_mrdr is 0.7878674506406875
.

================================================== 17 passed in 10.50s ==================================================
```

**Comment by fullflu** [comment]
@nmasahiro 

In my test code, flake8 gives several warnings.
How should I fix them?
```
% flake8 tests/
tests/ope/test_all_estimators.py:110:13: W503 line break before binary operator
tests/ope/test_all_estimators.py:114:13: W503 line break before binary operator
tests/ope/test_regression_models.py:6:1: F401 'sklearn.experimental.enable_hist_gradient_boosting' imported but unused
```

- I think W503 (& W504) should be ignored in `setup.cfg` because it is incompatible with black.
- The problem of `sklearn.experimental.enable_hist_gradient_boosting` could be ignored in this test because it would be a temporary problem of scikit-learn.

**Comment by nmasahiro** [comment]
@fullflu 

> I think W503 should be ignored in setup.cfg because it is incompatible with black.

LGTM. Can you add W503 to `setup.cfg`?

> The problem of sklearn.experimental.enable_hist_gradient_boosting could be ignored in this test 

I'm sorry, I still don't understand the problem exactly.
I couldn't find any part of your code that uses `enable_hist_gradient_boosting`.
Where do you need it?

**Comment by fullflu** [comment]
> LGTM. Can you add W503 to setup.cfg?

OK!

> Where do you need it?

To use `sklearn.ensemble.HistGradientBoostingClassifier`, we need to explicitly import enable_hist_gradient_boosting unless it is not called:
https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.HistGradientBoostingClassifier.html#sklearn.ensemble.HistGradientBoostingClassifier

However, the warning was ignored by using `# noqa` comment.

Flake8 now gives no warning 🎉

**Comment by usaito** [comment]
@fullflu 
Thanks! LGTM!

**Pull request merged**
