### PR TITLE
Contribution guidelines

### PR DESCRIPTION
**Pull request by nmasahiro**
## Motivation
Related to https://github.com/st-tech/zr-obp/issues/32.

### CODE REVIEW

**Comment by usaito** [comment]
@nmasahiro  Thanks! Some minor comments below:
- `to be appear` shoud be `to appear`
- Can you add some description about the contribution in (root) README.md?

**Comment by nmasahiro** [comment]
@usaito 
Thank you for the review.
I fixed the grammatical error and added the description of the contributing to README.md. PTAL.

**Comment by usaito** [comment]
@nmasahiro Thanks! LGTM. Let's wait for Takayama-san's review

**Comment by fullflu** [comment]
Thanks!

@nmasahiro 
[imo]
If possible, it would be better to explain minimum rules of PR such as:
- Branch naming rule (no rule might be OK at the moment)
- PR model (`folk & pull model` or `shared repository model`: I prefer the former)

**Comment by nmasahiro** [comment]
@fullflu 
Thank you for the helpful suggestion.

> Branch naming rule

Currently, I have no idea about this.
@usaito @fullflu 
Do you have any good ideas?

> PR model

I also like the folk & pull model. On the other hand, currently, pushing to this repository requires authority and does not become a shared repository model, so I feel that it is not necessary to specify it in particular.

**Comment by fullflu** [comment]
> Branch naming rule

@usaito seems to have used four types of branch names.
- feat/foo
- fix/foo
- hotfix/foo
- foo

I propose simple rules such as:
- **feature/foo**: when we add new features to the library
- **fix/foo**: when we fix several bugs or typos
- **release/x.y.z**: when we release a new version, `x.y.z` (this would be based on gitlab-flow)

> pushing to this repository requires authority and does not become a shared repository model, so I feel that it is not necessary to specify it in particular

Oh, I did not notice it!
I agree with you.

**Comment by nmasahiro** [comment]
I am concerned that there are many cases that are not included in the above rules.
Where are refactoring, test, ci, for example? (Because these are not features.)

And I still don't understand why branch names should be regularized, so I'd be happy to hear about that :)

**Comment by fullflu** [comment]
I was thinking that the branch name could be used as a trigger of CI in the future, but it might be out of scope of this PR (sorry)..

I approve it 🎉

**Comment by nmasahiro** [comment]
@fullflu 
In my current understanding,

* CI always should check whether the test successes.
* It is not necessary to deploy automatically (because the release process is based on versioning).

Therefore, I think checking the branch names may not be necessary.
However, as you said, it is better to discuss the CI design (e.g., what is the trigger?) when introducing CI.
Thank you for the useful discussion!

@usaito 
Please merge this PR if you are OK.

**Pull request merged**
