### PR TITLE
add test policy offline unittest

### PR DESCRIPTION
**Pull request by nmasahiro**
## Overview

Add several tests for the policy **offline** module.

```
$ pytest -s

============================= test session starts ==============================
platform darwin -- Python 3.7.1, pytest-6.2.1, py-1.10.0, pluggy-0.13.1 -- /Users/a14752/Documents/research/OPE/code/zr-obp/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/a14752/Documents/research/OPE/code/zr-obp
collecting ... collected 5 items

test/policy/test_offline.py::test_base_opl_init PASSED                   [ 20%]
test/policy/test_offline.py::test_ipw_learner_init PASSED                [ 40%]
test/policy/test_offline.py::test_create_train_data_for_opl PASSED       [ 60%]
test/policy/test_offline.py::test_opl_fit PASSED                         [ 80%]
test/policy/test_offline.py::test_opl_predict PASSED                     [100%]

```

## Review points
* Testing structure
* Testing code

## Remark
* This test has verified the behavior of the algorithm, but not the performance.
* After adding other package unittests (e.g., datasets), we will add e2e tests to verify the performance improvement.

### CODE REVIEW

**Comment by usaito** [comment]
@nmasahiro 
Thanks!

[nits]
https://github.com/nmasahiro/zr-obp/blob/8a2863e4d8f94bb7e13b42840233e55b92cc1e04/test/policy/test_offline.py#L113
`context_test` would be more understandable than `context_predict` 

Moreover, can you add some verifications about the `sample_action` method below?
https://github.com/st-tech/zr-obp/blob/55ab57ea214db3e69550e48c466ca8d52074145e/obp/policy/offline.py#L231

**Comment by nmasahiro** [comment]
@usaito 
Sorry for the late reply.
I've fixed the above points, so please check.

**Comment by usaito** [comment]
@nmasahiro 
Thanks! LGTM!

**Comment by usaito** [comment]
@nmasahiro 
Can you modify the directory name to `tests`?

**Comment by nmasahiro** [comment]
@usaito Yeah! I've fixed, so please check.

**Comment by usaito** [comment]
@nmasahiro Thanks! LGTM

**Pull request merged**
